spring.application.name=dog-seizure-tracker

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/dog-seizure_tracker_app?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
logging.level.org.hibernate.persister.entity=ERROR
spring.web.resources.cache.period=3600

spring.profiles.active=dev
spring.mvc.hiddenmethod.filter.enabled=true

#User properties
users.defaultUser.username=defaultUser
users.defaultUser.password=defaultPassword
users.defaultUser.firstName=defaultFirstName
users.defaultUser.lastName=defaultLastName
users.defaultUser.email=defaultEmail